name: Push To Dev

on:
  push:
    branches:
      - dev

jobs:
  services:
    # Label used to access the service container
    postgres_app:
      # Docker Hub image
      image: postgres
      # Provide the password for postgres
      env:
        POSTGRES_PASSWORD: password
      # Set health checks to wait until postgres has started
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run Docker Compose
      run: | 
        docker-compose up -d
        docker exec todo_app npm run test
      env:
        CI: true
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
        POSTGRES_HOST: postgres_app
        POSTGRES_PORT: 5432